# Generated by Django 3.0.7 on 2020-06-17 18:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
